# Copyright (C) 2022 SanCloud Ltd
# SPDX-License-Identifier: Apache-2.0

stages:
  - check
  - build
  - deploy

.check:
  stage: check
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always

.build:
  image: quay.io/podman/stable
  stage: build
  resource_group: registry  # This ensures only one build runs at a time so that
                            # local image names are not rebuilt concurrently.
  variables:
    DEFAULT_REPO: "${CI_REGISTRY}/${CI_PROJECT_PATH}"

.deploy:
  stage: deploy
  resource_group: registry  # This ensures only one build runs at a time so that
                            # local image names are not rebuilt concurrently.
  rules:
    - if: $CI_COMMIT_TAG
  variables:
    DEFAULT_REPO: "${CI_REGISTRY}/${CI_PROJECT_PATH}"
    EXTRA_REPO_ARGS: quay.io/sancloudltd

.deploy-internal:
  extends: .deploy
  image: quay.io/podman/stable
  before_script:
    - podman login -u ${CI_REGISTRY_USER} -p ${CI_JOB_TOKEN} ${CI_REGISTRY}

.deploy-external:
  extends: .deploy
  tags:
    - container-test
  before_script:
    - echo "${QUAY_BOT_TOKEN}" | docker login quay.io --username='sancloudltd+bot' --password-stdin

hadolint:
  extends: .check
  image: hadolint/hadolint:latest-alpine
  script:
    - hadolint ./**/Containerfile
    - hadolint ./base/**/Containerfile

pre-commit:
  extends: .check
  image: gitlab-registry.sancloud.co.uk/tools/containers/pre-commit:${PRECOMMIT_VER}
  script:
    - pre-commit run -a

build-base-images:
  extends: .build
  script:
    - ./scripts/build.py -a -r ${DEFAULT_REPO} -t ${CI_COMMIT_REF_SLUG} -D base

build-images:
  extends: .build
  needs:
    - build-base-images
  script:
    - ./scripts/build.py -a -r ${DEFAULT_REPO} -t ${CI_COMMIT_REF_SLUG}

deploy-base-images-internal:
  extends: .deploy-internal
  needs:
    - build-base-images
  script:
    - ./scripts/build.py -a -d -r ${DEFAULT_REPO} -t ${CI_COMMIT_REF_SLUG}

deploy-images-internal:
  needs:
    - build-images
  extends: .deploy-internal
  script:
    - ./scripts/build.py -a -d -r ${DEFAULT_REPO} -t ${CI_COMMIT_REF_SLUG} -D ./base


deploy-base-images-external:
  extends: .deploy-external
  script:
    - ./scripts/build.py -a -d -r ${EXTRA_REPO_ARGS} -t latest -D ./base

deploy-images-external:
  needs:
    - deploy-base-images-external
  extends: .deploy-external
  script:
    - ./scripts/build.py -a -d -r ${EXTRA_REPO_ARGS} -t latest
