# Copyright (C) 2022 SanCloud Ltd
# SPDX-License-Identifier: Apache-2.0

stages:
  - check
  - build

hadolint:
  stage: check
  image: hadolint/hadolint:latest-alpine
  script:
    - hadolint iot-build/Containerfile
    - hadolint iot-arm-build/Containerfile
    - hadolint poky-build/Containerfile
    - hadolint arago-build/Containerfile
    - hadolint dev23-base/Containerfile
    - hadolint dev23-c/Containerfile
    - hadolint dev23-yocto/Containerfile

pre-commit:
  stage: check
  image: gitlab-registry.sancloud.co.uk/bsp/build-containers/dev23-base:latest
  script:
    - pre-commit run -a

build-images:
  image: quay.io/podman/stable
  stage: build
  resource_group: registry  # This ensures only one build runs at a time so that
                            # local image names are not rebuilt concurrently.
  rules:
    - if: $CI_COMMIT_REF_SLUG == "main"
      variables:
        CTR_TAG: latest
        EXTRA_REPO_ARGS: -r quay.io/sancloudltd
    - if: $CI_COMMIT_REF_SLUG != "main"
      variables:
        CTR_TAG: $CI_COMMIT_REF_SLUG
  variables:
    DEFAULT_REPO: "${CI_REGISTRY}/${CI_PROJECT_PATH}"
  before_script:
    - podman login -u ${CI_REGISTRY_USER} -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - |
      if [[ "$CTR_TAG" == latest ]]; then
        podman login -u "sancloudltd+bot" -p "${QUAY_BOT_TOKEN}" quay.io
      fi
  script:
    - ./scripts/build.py -a -d -r ${DEFAULT_REPO} ${EXTRA_REPO_ARGS} -t ${CTR_TAG}
