# Copyright (C) 2022 SanCloud Ltd
# SPDX-License-Identifier: Apache-2.0

stages:
  - check
  - build

hadolint:
  stage: check
  image: hadolint/hadolint:latest-alpine
  script:
    - hadolint iot-build/Containerfile
    - hadolint iot-arm-build/Containerfile
    - hadolint poky-build/Containerfile
    - hadolint arago-build/Containerfile

pre-commit:
  stage: check
  image: gitlab-registry.sancloud.co.uk/bsp/build-containers/iot-build:latest
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  cache:
    paths:
      - ${PRE_COMMIT_HOME}
  script:
    - pre-commit run -a

.build-container:
  image: quay.io/podman/stable
  stage: build
  rules:
    - if: $CI_COMMIT_REF_SLUG == "main"
      variables:
        CTR_TAG: latest
    - if: $CI_COMMIT_REF_SLUG != "main"
      variables:
        CTR_TAG: $CI_COMMIT_REF_SLUG
  variables:
    CTR_NAME: "${CI_REGISTRY}/${CI_PROJECT_PATH}/${CI_JOB_NAME}:${CTR_TAG}"
    QUAY_CTR_NAME: "quay.io/sancloudltd/${CI_JOB_NAME}:latest"
  script:
    - echo ${CTR_NAME}
    - podman login -u ${CI_REGISTRY_USER} -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - podman build --pull -t "${CTR_NAME}" ${EXTRA_PODMAN_BUILD_ARGS} ${CI_JOB_NAME}
    - podman push "${CTR_NAME}"
    - |
      if [[ "$CTR_TAG" == latest ]]; then
        podman tag "${CTR_NAME}" "${QUAY_CTR_NAME}"
        podman login -u "sancloudltd+bot" -p "${QUAY_BOT_TOKEN}" quay.io
        podman push "${QUAY_CTR_NAME}"
      fi

iot-build:
  extends: .build-container

iot-arm-build:
  extends: .build-container
  variables:
    EXTRA_PODMAN_BUILD_ARGS: --from "${CI_REGISTRY}/${CI_PROJECT_PATH}/iot-build:${CTR_TAG}"
  dependencies:
    - iot-build

poky-build:
  extends: .build-container

arago-build:
  extends: .build-container
  variables:
    EXTRA_PODMAN_BUILD_ARGS: --from "${CI_REGISTRY}/${CI_PROJECT_PATH}/poky-build:${CTR_TAG}"
  dependencies:
    - poky-build
