# Copyright (C) 2021 SanCloud Ltd
# SPDX-License-Identifier: Apache-2.0

name: "Build image"
description: "Builds and deploys a container image"
inputs:
  gh-username:
    required: true
    description: "GitHub username"
  gh-token:
    required: true
    description: "GitHub access token"
  image-name:
    required: true
    description: "Name of the image to build"
  image-description:
    required: true
    description: "Description of the image to build"
runs:
  using: composite
  steps:
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/sancloudltd/${{ inputs.image-name }}
        labels: |
          org.opencontainers.image.title=${{ inputs.image-name }}
          org.opencontainers.image.description=${{ inputs.image-description }}

    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ inputs.gh-username }}
        password: ${{ inputs.gh-token }}

    - name: Run pre-build script
      shell: bash
      run: if [ -e prebuild.sh ]; then NOPULL=1 ./prebuild.sh; fi
      working-directory: ${{ inputs.image-name }}

    - name: Build and publish
      uses: docker/build-push-action@v2
      with:
        pull: true
        push: true
        context: ${{ inputs.image-name }}
        file: ${{ inputs.image-name }}/Containerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
