# Copyright (C) 2023 SanCloud Ltd
# SPDX-License-Identifier: Apache-2.0

FROM docker.io/library/ubuntu:22.04

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
        build-essential wget file openssh-client ca-certificates \
        git rsync python3 python3-pip ruby && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    python3 -m pip install --no-cache-dir --upgrade pre-commit identify && \
    git config --system --add safe.directory '*'
