# Copyright (C) 2021 SanCloud Ltd
# SPDX-License-Identifier: Apache-2.0

FROM iot-build:latest

ENV TOOLCHAIN_VENDOR=bootlin
ENV TOOLCHAIN_ARCH=armv7-eabihf
ENV TOOLCHAIN_LIBC=glibc
ENV TOOLCHAIN_BRANCH=stable
ENV TOOLCHAIN_VERSION=2025.08-1
ENV TOOLCHAIN_FULLNAME=${TOOLCHAIN_ARCH}--${TOOLCHAIN_LIBC}--${TOOLCHAIN_BRANCH}-${TOOLCHAIN_VERSION}

RUN apt-get update -y&& \
    DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    libgnutls28-dev \
    pkg-config && \
	wget --progress=dot:mega \
        "https://toolchains.bootlin.com/downloads/releases/toolchains/${TOOLCHAIN_ARCH}/tarballs/${TOOLCHAIN_FULLNAME}.tar.xz" && \
    tar -C /opt -xf "${TOOLCHAIN_FULLNAME}.tar.xz" && \
    rm -f "${TOOLCHAIN_FULLNAME}.tar.xz" && \
    ln -sfn "${TOOLCHAIN_FULLNAME}" /opt/toolchain && \
    /opt/toolchain/relocate-sdk.sh&& \
    rm -rf /var/lib/apt/lists/*

COPY setenv "/opt/toolchain/setenv"
