# Copyright (C) 2023 SanCloud Ltd
# SPDX-License-Identifier: Apache-2.0

FROM docker.io/crops/poky:ubuntu-22.04

USER root
RUN wget --progress=dot:mega https://bootstrap.pypa.io/get-pip.py && \
    python3 get-pip.py && \
    rm get-pip.py && \
    python3 -m pip install --no-cache-dir kas git-acquire && \
    echo 'StrictHostKeyChecking accept-new' >> /etc/ssh/ssh_config && \
    wget --progress=dot:mega \
        https://storage.googleapis.com/git-repo-downloads/repo \
        -O /usr/local/bin/repo && \
    chmod a+rx /usr/local/bin/repo && \
    git config --system --add safe.directory '*' && \
    git config --system user.name poky-build && \
    git config --system user.email nobody@example.com

USER usersetup
