# Copyright (C) 2021 SanCloud Ltd
# SPDX-License-Identifier: Apache-2.0

name: Build images
on:
  push:
    branches: ['dev', 'release']
    tags: ['v*']
  schedule:
    # Build at 00:10 on Mondays
    - cron: '10 0 * * 1'

jobs:
  base-images:
    name: Base images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: iot-dev
            description: IoT development environment
          - image: poky-build
            description: Yocto Project build environment for Poky distro
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and deploy image
        uses: ./.github/actions/build-image
        with:
          gh-username: ${{ github.actor }}
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: ${{ matrix.image }}
          image-description: ${{ matrix.description }}

  derived-images:
    name: Derived images
    runs-on: ubuntu-latest
    needs: base-images
    strategy:
      matrix:
        include:
          - image: iot-crossdev
            description: IoT development environment with cross-compilation toolchain
          - image: arago-build
            description: Yocto Project build environment for Arago distro
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and deploy image
        uses: ./.github/actions/build-image
        with:
          gh-username: ${{ github.actor }}
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: ${{ matrix.image }}
          image-description: ${{ matrix.description }}
