# Copyright (C) 2021 SanCloud Ltd
# SPDX-License-Identifier: Apache-2.0

name: CI
on:
  push:
    branches: ['dev', 'release']
    tags: ['v*']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Run pre-commit checks
        uses: pre-commit/action@v2.0.3

  base-images:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      matrix:
        include:
          - image: iot-dev
            description: IoT development environment
          - image: poky-build
            description: Yocto Project build environment for Poky distro
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/sancloudltd/${{ matrix.image }}
          labels: |
            org.opencontainers.image.title=${{ matrix.image }}
            org.opencontainers.image.description=${{ matrix.description }}

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run pre-build script
        run: if [ -e prebuild.sh ]; then NOPULL=1 ./prebuild.sh; fi
        working-directory: ${{ matrix.image }}

      - name: Build and publish
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{ matrix.image }}
          file: ${{ matrix.image }}/Containerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  derived-images:
    runs-on: ubuntu-latest
    needs: base-images
    strategy:
      matrix:
        include:
          - image: iot-crossdev
            description: IoT development environment with cross-compilation toolchain
          - image: arago-build
            description: Yocto Project build environment for Arago distro
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/sancloudltd/${{ matrix.image }}
          labels: |
            org.opencontainers.image.title=${{ matrix.image }}
            org.opencontainers.image.description=${{ matrix.description }}

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run pre-build script
        run: if [ -e prebuild.sh ]; then NOPULL=1 ./prebuild.sh; fi
        working-directory: ${{ matrix.image }}

      - name: Build and publish
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{ matrix.image }}
          file: ${{ matrix.image }}/Containerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
