# Copyright (C) 2021 SanCloud Ltd
# SPDX-License-Identifier: Apache-2.0

name: CI
on:
  push:
    branches: ['dev', 'release']
    tags: ['v*']

jobs:
  base-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ['iot-dev', 'poky-build']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/sancloudltd/${{ matrix.image }}

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{ matrix.image }}
          file: ${{ matrix.image }}/Containerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  derived-images:
    runs-on: ubuntu-latest
    needs: base-images
    strategy:
      matrix:
        image: ['iot-crossdev', 'arago-build']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/sancloudltd/${{ matrix.image }}

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ${{ matrix.image }}
          file: ${{ matrix.image }}/Containerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
